### ISSUE TITLE
Infinite results with Pytx generator

### ISSUE THREAD

**Issue by vraja2** [facebook/ThreatExchange#215]
When using Pytx as follows
```
>>> iter = ThreatDescriptor.objects(since='1576462455', until='1576469851', type_='HASH_MD5')
>>> for i in iter:
...     print(i)
```

I'm getting an infinite stream of results and the loop never concludes. However, when I use

```
>>> results = ThreatDescriptor.objects(since='1576462455', until='1576469851', type_='HASH_MD5', full_response=True)
```
the results are finite. Can you reproduce/is there an issue with the generator logic?

Thanks.

**Comment by vraja2** [comment]
@mgoffin @johnkerl

**Comment by johnkerl** [comment]
Thanks @vraja2 -- I will check this out. :)

**Comment by mgoffin** [comment]
The generator continuing to loop depends on the `CURSOR` values returned in the response as part of the `PAGING` done server-side to limit the amount of results that are returned each time. If that has some value, it will continue to run.

https://github.com/facebook/ThreatExchange/blob/master/pytx/pytx/request.py#L499

You can setup a logger (https://github.com/facebook/ThreatExchange/blob/master/pytx/pytx/logger.py#L27) to review the `CURSOR` values (https://github.com/facebook/ThreatExchange/blob/master/pytx/pytx/request.py#L508). It should show you what the server is providing as the cursor to follow as you request the next set of results. This comes in a `BEFORE` and `AFTER` allowing you to page back and forth. Theoretically once there are no more results the server shouldn't provide you with an `AFTER`. If it continues to do so, the server is what is telling you more stuff is available.

Then again, this was years ago and I have no clue what they've changed since then :)

**Comment by johnkerl** [comment]
@vraja2 / @mgoffin I believe this is a server-side issue, independent of the client-side Python library. I'll keep you posted.

**Comment by vraja2** [comment]
Thanks both for looking into it!

A server-side issue is the conclusion I came to as well since the `AFTER` cursor value is always non-empty.

**Comment by johnkerl** [comment]
As a side note, this dovetails nicely with current development work on the in-development power-search feature for the new ThreatExchange UI (https://developers.facebook.com/docs/threat-exchange/ui).

**Comment by vraja2** [comment]
@johnkerl Just tried using the generator again and looks like the server-side issue was resolved!

**Comment by johnkerl** [comment]
@vraja2 glad to hear it ... although there is an ongoing known issue with longer paginated queries. Glad to hear your immediate symptom is resolved, though ...

**Comment by vraja2** [comment]
Ok never mind, it seems like the issue is still happening when using a more recent time-range (the last 2 hours). The original time-range in question is working now however, so there is some odd behavior going on there.

**Comment by johnkerl** [comment]
@vraja2 that makes sense. I believe the issue is with pagination, for when the size of the result-set exceeds a page in the backend.

**Comment by vraja2** [comment]
@johnkerl Happy New Year! Just pinging to see if there was any progress on the pagination issue.

**Comment by johnkerl** [comment]
Hi @vraja2! Just got back from winter travel and starting back to work on Monday. This is one of my top priorities.

**Comment by vraja2** [comment]
Also seems this issue was resolved a while back, thanks!
